Initial_update
hbmuller/rush-js pull request #7
Opened 2019-10-24 21:03 UTC by ankitasharma88990

little grmmartical mistakes were correted to make look document nice.

2019-10-24 21:04 UTC, ankitasharma88990 commented
Please accept as it's the end of hacktoberfest.
Thankyou.

2019-10-24 21:05 UTC, IamAnkita-create reviewed
greate work!!

2019-10-25 21:19 UTC, koppor commented
Variable names must not take spaces. Thus, this PR should be flagged `invalid` as outlined at https://hacktoberfest.digitalocean.com/faq.

2019-11-19 18:43 UTC, hbmueller requested changes
The names of variables, properties and methods (eg. `myLayer`, `sourcePromise`, `autoResize` and such) can't take spaces or dashes. That's why they are supposed to be in camel case, like they are.

2019-11-19 18:43 UTC, hbmuller commented on README.md
> -Philately is a super easy to use rendering engine for HTML5 `<canvas>`. You have a renderer, some layers and that's all. Simple as that. Great for games, interactive media or just drawing some images
The article here was intended. In the sense of:

> [...] **a** super easy to use **rendering engine** [...]

2019-11-19 18:43 UTC, hbmuller commented on README.md
> -- `draw()`: Draws the layer stack to the target `<canvas>`. Specially useful to update the graphics when the engine `autoStart`
Good catch.

2019-11-19 18:43 UTC, hbmuller commented on README.md
> -- `onStep`: A function that is called before the each rendering cycle. The parameters passed are [`renderParams`](#renderParams)
Nice

2019-11-19 18:44 UTC, hbmuller commented
BTW, @ankitasharma88990 sorry for not reviewing your PR before. For some reason my email notifications were turned off and I only saw this today.

2019-11-19 18:45 UTC, hbmuller commented
Closed in favor of #6

2019-11-19 18:45 UTC, closed without merging